# cmake/LintDocs.cmake: the lint.docs CTest (ADR-93, the web lead phase). Run as a script:
#
#   cmake -DFCMP_SOURCE_DIR=<repository root> -P cmake/LintDocs.cmake
#
# The facts a document states that another file owns, and that drift silently when only the owner changes. Each check
# compares the two; any violation prints "<file>: <rule>: <text>" and fails the test. Nothing is built or run.
#   ci.jobs         every job id of .github/workflows/ci.yml is a list item "- `<id>`" of 03's CI section (the heading
#                   "CI (`.github/workflows/ci.yml`)"), and every such item is a job of ci.yml
#   agents.cap      the agent cap of CLAUDE.md ("At most <n> agents") is the cap wherever 03 or ARCHITECTURE states one
#                   ("at most <n> agents|at once", "≤ <n> agents|at once"; a digit or a word, ** allowed around it).
#                   docs/SPRINTS.md is not read: its §0.1 rule 1 and §3.1 step 3 were written for a cap of 3; it joins
#                   the list below once they state the cap of today
#   claude.presets  every preset CLAUDE.md names exists in CMakePresets.json, of the kind its command uses (cmake
#                   --preset: configure, --build: build, --workflow: workflow, ctest: test), and every visible
#                   configure preset is one of CLAUDE.md's preset list (its "  - `<name>` —" items and its "lead only"
#                   line): a preset added without the agents' rules fails here
#   docs.scripts    every Scripts/<path> that CLAUDE.md, README.md, ARCHITECTURE.md, DECISIONS.md, SPRINTS.md, 01 or 03
#                   names exists (a file or a directory; 02 is not read: its seed table names HardwareReverb's scripts)
#   readme.modes    the number of Modes README.md states ("<Word> compressor types, called **Modes**") and the rows of
#                   its Modes table both equal the FCMP_MODE lines of Source/fcdsp/modes/Modes.def
# Labels verify;lint;global (cmake/FcmpProbes.cmake, beside lint.deps), in every configuration.
cmake_minimum_required(VERSION 3.30)

if(NOT FCMP_SOURCE_DIR)
  get_filename_component(FCMP_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
set(_root "${FCMP_SOURCE_DIR}")
set_property(GLOBAL PROPERTY FCMP_DOCS_VIOLATIONS 0)

function(_docs_fail file rule text)
  message("${file}: ${rule}: ${text}")
  get_property(_n GLOBAL PROPERTY FCMP_DOCS_VIOLATIONS)
  math(EXPR _n "${_n} + 1")
  set_property(GLOBAL PROPERTY FCMP_DOCS_VIOLATIONS ${_n})
endfunction()

# _docs_read(<out> <relative path>): the file's text with the characters CMake lists cannot hold neutralised
# (';' -> ',', '[' -> '{', ']' -> '}', '\' -> '/'), as LintDeps.cmake does. None of the checks depends on them.
function(_docs_read out rel)
  if(NOT EXISTS "${_root}/${rel}")
    _docs_fail("${rel}" missing "the file does not exist")
    set(${out} "" PARENT_SCOPE)
    return()
  endif()
  file(READ "${_root}/${rel}" _c)
  string(REPLACE "\r" "" _c "${_c}")
  string(REPLACE "\\" "/" _c "${_c}")
  string(REPLACE ";" "," _c "${_c}")
  string(REPLACE "[" "{" _c "${_c}")
  string(REPLACE "]" "}" _c "${_c}")
  set(${out} "${_c}" PARENT_SCOPE)
endfunction()

# _docs_lines(<out> <text>): the text as a CMake list, one element per line (empty lines kept).
function(_docs_lines out text)
  string(REPLACE "\n" ";" _l "${text}")
  set(${out} "${_l}" PARENT_SCOPE)
endfunction()

# A number written as a digit or as a word (zero to thirty-nine), or "" when it is neither.
set(_units zero one two three four five six seven eight nine ten eleven twelve thirteen fourteen fifteen sixteen
           seventeen eighteen nineteen)
function(_docs_number out word)
  string(TOLOWER "${word}" _w)
  if(_w MATCHES "^[0-9]+$")
    set(${out} ${_w} PARENT_SCOPE)
    return()
  endif()
  list(FIND _units "${_w}" _i)
  if(_i GREATER -1)
    set(${out} ${_i} PARENT_SCOPE)
    return()
  endif()
  if(_w MATCHES "^(twenty|thirty)(-([a-z]+))?$")
    set(_tens 20)
    if(CMAKE_MATCH_1 STREQUAL "thirty")
      set(_tens 30)
    endif()
    set(_u 0)
    if(CMAKE_MATCH_3)
      list(FIND _units "${CMAKE_MATCH_3}" _u)
    endif()
    if(_u GREATER 0 AND _u LESS 10)
      math(EXPR _v "${_tens} + ${_u}")
      set(${out} ${_v} PARENT_SCOPE)
      return()
    elseif(NOT CMAKE_MATCH_3)
      set(${out} ${_tens} PARENT_SCOPE)
      return()
    endif()
  endif()
  set(${out} "" PARENT_SCOPE)
endfunction()

set(_checks 0)

# ---- ci.jobs ---------------------------------------------------------------------------------------------------------
math(EXPR _checks "${_checks} + 1")
set(_ci_rel .github/workflows/ci.yml)
set(_d03_rel docs/design/03-build-verify-process.md)
_docs_read(_ci "${_ci_rel}")
_docs_lines(_ci_lines "${_ci}")
set(_jobs "")
set(_in_jobs FALSE)
foreach(_l IN LISTS _ci_lines)
  if(_l MATCHES "^jobs:[ \t]*$")
    set(_in_jobs TRUE)
  elseif(_in_jobs AND _l MATCHES "^[^ \t#]")
    set(_in_jobs FALSE)                                        # the next top-level key
  elseif(_in_jobs AND _l MATCHES "^  ([A-Za-z0-9_-]+):[ \t]*(#.*)?$")
    list(APPEND _jobs ${CMAKE_MATCH_1})
  endif()
endforeach()
if(NOT _jobs)
  _docs_fail("${_ci_rel}" ci.jobs "no job found under `jobs:`")
endif()
_docs_read(_d03 "${_d03_rel}")
_docs_lines(_d03_lines "${_d03}")
set(_named "")
set(_in_ci FALSE)
set(_seen_ci FALSE)
foreach(_l IN LISTS _d03_lines)
  if(_l MATCHES "^#+ .*CI \\(`\\.github/workflows/ci\\.yml`\\)")
    set(_in_ci TRUE)
    set(_seen_ci TRUE)
  elseif(_in_ci AND _l MATCHES "^#")
    set(_in_ci FALSE)
  elseif(_in_ci AND _l MATCHES "^- `([A-Za-z0-9_-]+)`")
    list(APPEND _named ${CMAKE_MATCH_1})
  endif()
endforeach()
if(NOT _seen_ci)
  _docs_fail("${_d03_rel}" ci.jobs "no section headed \"CI (`.github/workflows/ci.yml`)\"")
endif()
list(REMOVE_DUPLICATES _named)
foreach(_j IN LISTS _jobs)
  if(NOT _j IN_LIST _named)
    _docs_fail("${_d03_rel}" ci.jobs "the CI job `${_j}` of ${_ci_rel} is not a \"- `${_j}`\" item of the CI section")
  endif()
endforeach()
foreach(_j IN LISTS _named)
  if(NOT _j IN_LIST _jobs)
    _docs_fail("${_d03_rel}" ci.jobs "the CI section names `${_j}`, which is not a job of ${_ci_rel}")
  endif()
endforeach()

# ---- agents.cap ------------------------------------------------------------------------------------------------------
math(EXPR _checks "${_checks} + 1")
set(_cap_re "(At most|at most|≤)[ *]*([0-9]+|[A-Za-z]+)[ *]+(agents|at once)")
_docs_read(_claude CLAUDE.md)
set(_cap "")
if(_claude MATCHES "At most ([0-9]+) agents")
  set(_cap ${CMAKE_MATCH_1})
else()
  _docs_fail(CLAUDE.md agents.cap "states no agent cap (\"At most <n> agents\")")
endif()
if(_cap)
  foreach(_rel docs/design/03-build-verify-process.md docs/ARCHITECTURE.md)
    _docs_read(_t "${_rel}")
    string(REGEX REPLACE "[ \t]*\n[ \t]*" " " _t "${_t}")        # a statement may wrap
    string(REGEX MATCHALL "${_cap_re}" _hits "${_t}")
    foreach(_h IN LISTS _hits)
      if(_h MATCHES "${_cap_re}")
        _docs_number(_n "${CMAKE_MATCH_2}")
        if(_n STREQUAL "")
          continue()                                           # "at most several agents": no number stated
        endif()
        if(NOT _n EQUAL _cap)
          _docs_fail("${_rel}" agents.cap "says '${_h}', but CLAUDE.md's cap is ${_cap}")
        endif()
      endif()
    endforeach()
  endforeach()
endif()

# ---- claude.presets --------------------------------------------------------------------------------------------------
math(EXPR _checks "${_checks} + 1")
file(READ "${_root}/CMakePresets.json" _json)
foreach(_kind configure build test workflow)
  set(_have_${_kind} "")
  set(_visible_${_kind} "")
  string(JSON _n ERROR_VARIABLE _err LENGTH "${_json}" ${_kind}Presets)
  if(_err)
    continue()
  endif()
  if(_n GREATER 0)
    math(EXPR _last "${_n} - 1")
    foreach(_i RANGE ${_last})
      string(JSON _name GET "${_json}" ${_kind}Presets ${_i} name)
      string(JSON _hidden ERROR_VARIABLE _e2 GET "${_json}" ${_kind}Presets ${_i} hidden)
      list(APPEND _have_${_kind} ${_name})
      if(_e2 OR NOT _hidden)
        list(APPEND _visible_${_kind} ${_name})
      endif()
    endforeach()
  endif()
endforeach()
string(REGEX REPLACE "[ \t]*\n[ \t]*" " " _flat "${_claude}")  # a command may wrap
string(REGEX MATCHALL "(cmake|ctest)( --workflow| --build)? --preset[ =][a-z0-9-]+" _cmds "${_flat}")
foreach(_c IN LISTS _cmds)
  string(REGEX MATCH "^(cmake|ctest)( --workflow| --build)? --preset[ =]([a-z0-9-]+)$" _m "${_c}")
  set(_name ${CMAKE_MATCH_3})
  if(CMAKE_MATCH_1 STREQUAL "ctest")
    set(_kind test)
  elseif(CMAKE_MATCH_2 STREQUAL " --workflow")
    set(_kind workflow)
  elseif(CMAKE_MATCH_2 STREQUAL " --build")
    set(_kind build)
  else()
    set(_kind configure)
  endif()
  if(NOT _name IN_LIST _visible_${_kind})
    _docs_fail(CLAUDE.md claude.presets "'${_c}': CMakePresets.json has no ${_kind} preset `${_name}`")
  endif()
endforeach()
_docs_lines(_claude_lines "${_claude}")
set(_listed "")
foreach(_l IN LISTS _claude_lines)
  if(_l MATCHES "^  - `([a-z0-9-]+)` — ")
    list(APPEND _listed ${CMAKE_MATCH_1})
  elseif(_l MATCHES "^  - `[a-z0-9-]+`(, `[a-z0-9-]+`)*: lead only")
    string(REGEX MATCHALL "`[a-z0-9-]+`" _names "${_l}")
    foreach(_q IN LISTS _names)
      string(REPLACE "`" "" _q "${_q}")
      list(APPEND _listed ${_q})
    endforeach()
  endif()
endforeach()
if(NOT _listed)
  _docs_fail(CLAUDE.md claude.presets
             "no preset list found (\"  - `<name>` — ...\" items and a \"...: lead only\" line)")
endif()
foreach(_p IN LISTS _listed)
  if(NOT _p IN_LIST _visible_configure)
    _docs_fail(CLAUDE.md claude.presets "lists `${_p}`, which is not a configure preset of CMakePresets.json")
  endif()
endforeach()
if(_listed)
  foreach(_p IN LISTS _visible_configure)
    if(NOT _p IN_LIST _listed)
      _docs_fail(CLAUDE.md claude.presets "the configure preset `${_p}` is not in CLAUDE.md's preset list")
    endif()
  endforeach()
endif()

# ---- docs.scripts ----------------------------------------------------------------------------------------------------
math(EXPR _checks "${_checks} + 1")
foreach(_rel CLAUDE.md README.md docs/ARCHITECTURE.md docs/DECISIONS.md docs/SPRINTS.md
             docs/design/01-core-contracts.md docs/design/03-build-verify-process.md)
  _docs_read(_t "${_rel}")
  string(REGEX MATCHALL "Scripts/[A-Za-z0-9_.-]+(/[A-Za-z0-9_.-]+)*" _paths "${_t}")
  list(REMOVE_DUPLICATES _paths)
  foreach(_p IN LISTS _paths)
    string(REGEX REPLACE "[.]+$" "" _p "${_p}")                # a sentence's full stop
    if(NOT EXISTS "${_root}/${_p}")
      _docs_fail("${_rel}" docs.scripts "names ${_p}, which does not exist")
    endif()
  endforeach()
endforeach()

# ---- readme.modes ----------------------------------------------------------------------------------------------------
math(EXPR _checks "${_checks} + 1")
file(STRINGS "${_root}/Source/fcdsp/modes/Modes.def" _modes REGEX "^FCMP_MODE\\(")
list(LENGTH _modes _n_modes)
_docs_read(_readme README.md)
if(_readme MATCHES "([A-Z][a-z]+(-[a-z]+)?) compressor types, called \\*\\*Modes\\*\\*")
  set(_word "${CMAKE_MATCH_1}")
  _docs_number(_said "${_word}")
  if(NOT _said STREQUAL "${_n_modes}")
    _docs_fail(README.md readme.modes "says '${_word}' compressor types, but Modes.def has ${_n_modes} FCMP_MODE lines")
  endif()
else()
  _docs_fail(README.md readme.modes "states no number of Modes (\"<Word> compressor types, called **Modes**\")")
endif()
_docs_lines(_readme_lines "${_readme}")
set(_in_table FALSE)
set(_rows 0)
foreach(_l IN LISTS _readme_lines)
  if(_l MATCHES "^## Modes[ \t]*$")
    set(_in_table TRUE)
  elseif(_in_table AND _l MATCHES "^## ")
    break()
  elseif(_in_table AND _l MATCHES "^\\| " AND NOT _l MATCHES "^\\| (Mode|---) ")
    math(EXPR _rows "${_rows} + 1")
  endif()
endforeach()
if(NOT _rows EQUAL _n_modes)
  _docs_fail(README.md readme.modes "its Modes table has ${_rows} rows, but Modes.def has ${_n_modes} FCMP_MODE lines")
endif()

get_property(_bad GLOBAL PROPERTY FCMP_DOCS_VIOLATIONS)
string(JOIN " " _jobs_text ${_jobs})
message("lint.docs: ${_checks} checks (CI jobs: ${_jobs_text}; agent cap ${_cap}; ${_n_modes} Modes): "
        "${_bad} violation(s)")
if(_bad GREATER 0)
  message(FATAL_ERROR "lint.docs: ${_bad} violation(s)")
endif()
