#!/usr/bin/env python3
"""Generate docs/sprints/s<N>.md from docs/SPRINTS.md (lead tool; format of docs/sprints/s0.md).

usage: mkmanifest.py <repo> <N> <base-desc> <funkgui-pin-line> <frozen-line> [lead-revisions.md]
"""
import re, sys, textwrap
from pathlib import Path

repo, N, base, pin, frozen = Path(sys.argv[1]), int(sys.argv[2]), sys.argv[3], sys.argv[4], sys.argv[5]
revs = Path(sys.argv[6]).read_text() if len(sys.argv) > 6 else ""
plan = (repo / "docs/SPRINTS.md").read_text()
m = re.search(rf"^### Sprint {N} — (.*?)$(.*?)(?=^### Sprint {N+1} — |^## 5\. )", plan, re.M | re.S)
title, body = m.group(1).strip(), m.group(2)
cards = re.split(r"^#### ", body, flags=re.M)
head, cards = cards[0], cards[1:]
tail_m = re.search(r"^\*\*Ownership check S\d+\.\*\*.*", cards[-1], re.M | re.S)
tail = tail_m.group(0) if tail_m else ""
if tail_m:
    cards[-1] = cards[-1][: tail_m.start()]

def bullets(txt):
    out, key = {}, None
    for line in txt.splitlines():
        mm = re.match(r"^- \*\*(.+?)(?:\*\*|:\*\*)(.*)$", line)
        if mm:
            key = mm.group(1).rstrip(":. ").strip()
            out[key] = mm.group(2).lstrip(":. ").strip()
        elif key and line.startswith("  "):
            out[key] += " " + line.strip()
    return out

def clean(s):
    s = s.replace("\\*", "*")
    codes = []
    def keep(m):
        codes.append(m.group(1))
        return f"\x00{len(codes) - 1}\x00"
    s = re.sub(r"`([^`]*)`", keep, s)          # protect code spans (globs with **) before stripping bold
    s = re.sub(r"\*\*(.*?)\*\*", r"\1", s)
    return re.sub(r"\x00(\d+)\x00", lambda m: codes[int(m.group(1))], s)

def field(name, text, width=110):
    text = clean(text).strip()
    if not text:
        return f"{name:<8}(none)\n"
    lines = textwrap.wrap(text, width=width, break_long_words=False, break_on_hyphens=False)
    return f"{name:<8}{lines[0]}\n" + "".join(f"        {l}\n" for l in lines[1:])

out = [f"# Sprint {N} — {title}: task manifests\n",
       f"Status: **sprint base**, generated by the lead from `docs/SPRINTS.md` \"Sprint {N}\". Manifest format as in "
       f"`docs/sprints/s0.md` (read by `Scripts/sprint/ownership.py docs/sprints/s{N}.md#<ID> <worktree>`).\n",
       clean(head).strip() + "\n",
       f"**Base.** {base}\n", f"**FunkGui.** {pin}\n", f"**Frozen set.** {frozen}\n", "---\n"]
for c in cards:
    hm = re.match(r"S(\d+)\.(\d+) · (\S+?)\\?\*? · (.*?) — (FCompressor|FunkGui) · ([SML])", c)
    num, code, ttl, repo_name, size = f"S{hm.group(1)}.{hm.group(2)}", hm.group(3).rstrip("\\*"), hm.group(4), hm.group(5), hm.group(6)
    b = bullets(c)
    owns_key = next(k for k in b if k.startswith("OWNS"))
    owns = b[owns_key]
    branch = f"s{N}/{code.lower()}"
    where = (f"worktree: /Users/seanfunk/audio/libraries/FunkGui.wt/s{N}-{code.lower()}   branch: {branch}"
             if repo_name == "FunkGui" else f"branch: {branch} (rename the harness-made branch: git branch -m {branch})")
    blk = [f"TASK    {code}   card: {num}   repo: {repo_name}{' (isolation: worktree)' if repo_name == 'FCompressor' else ' (own worktree)'}   size: {size}\n",
           f"        {where}\n",
           field("GOAL", b.get("Goal", ttl)),
           field("OWNS", owns, width=118),
           field("FROZEN", frozen + " Every path outside OWNS: never edit."),
           field("FUNKGUI", pin),
           field("DONE", "03 §4.7 (ownership clean; no warnings; verify.sh 0 blocking; a reason per candidate group; "
                         "<= 60-line handoff) plus the Acceptance: " + b.get("Acceptance", "")),
           field("READS", b.get("Reads", "")),
           field("INPUTS", b.get("Inputs", "")),
           field("DELIVERABLES", "") if False else "DELIVERABLES\n" + "".join(
               f"        {l}\n" for l in textwrap.wrap(clean(b.get("Deliverables", "")), 110, break_long_words=False, break_on_hyphens=False)),
           field("NOTES", " ".join(f"{k}: {v}" for k, v in b.items() if k in ("Split seam", "K2") or k.startswith("Note")))]
    out.append(f"\n## {code}\n\n```text\n{''.join(blk)}```\n")
if revs:
    out.append("\n## Lead revisions at the S%d base\n\n%s\n" % (N, revs.strip()))
out.append("\n" + clean(tail).strip() + "\n")
out.append("\n## Outcome (the lead fills this in at the sprint end)\n\n- \n")
(repo / f"docs/sprints/s{N}.md").write_text("\n".join(out))
print(f"wrote docs/sprints/s{N}.md with", len(cards), "cards")
